[build]
  publish = "."
  
# Serve static files directly
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manage"
  to = "/manage.html"
  status = 200

# Handle SPA routing - serve index.html for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200