services:
  - type: web
    name: tbmcg-news-dashboard
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false  # You'll set this in Render dashboard
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET  
        sync: false
      - key: MICROSOFT_TENANT_ID
        sync: false
      - key: SECRET_KEY
        sync: false